project_name: qumine-server-java
release:
  github:
    owner: qumine
    name: qumine-server-java
before:
  hooks:
    - go mod download
builds:
- goos:
  - linux
  goarch:
  - amd64
  main: ./cmd/qumine-server-java
  binary: qumine-server-java
  env:
    - CGO_ENABLED=0
archives:
  - id: tar_gz
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
    - LICENSE*
    - README*
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
dockers:
  - dockerfile: build/package/Dockerfile
    image_templates:
      - "qumine/qumine-server-java:latest"
      - "qumine/qumine-server-java:{{.Tag}}"
    goos: linux
    goarch: amd64
changelog:
  filters:
    exclude:
      - '^ci:'
      - '^docs:'
      - '^misc:'
      - '^test:'