project_name: minecraft-server
release:
  github:
    owner: qumine
    name: minecraft-server
  prerelease: auto
before:
  hooks:
  - go mod download
builds:
- id: ""
  goos:
  - linux
  goarch:
  - amd64
  - arm64
  main: ./cmd/minecraft-server
  binary: minecraft-server
  env:
  - CGO_ENABLED=0
archives:
- id: tar_gz
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  files:
  - LICENSE*
  - README*
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
dockers:
- dockerfile: build/package/Dockerfile
  use: buildx
  image_templates:
  - "qumine/minecraft-server:latest-amd64"
  - "qumine/minecraft-server:{{.Tag}}-amd64"
  goos: linux
  goarch: amd64
  ids:
  - minecraft-server
  build_flag_templates:
  - "--platform=linux/amd64"
  - "--label=org.opencontainers.image.title={{ .ProjectName }}"
  - "--label=org.opencontainers.image.description={{ .ProjectName }}"
  - "--label=org.opencontainers.image.url=https://github.com/qumine/minecraft-server"
  - "--label=org.opencontainers.image.source=https://github.com/qumine/minecraft-server"
  - "--label=org.opencontainers.image.version={{ .Version }}"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
  - "--label=org.opencontainers.image.licenses=AGPL-3.0"
- dockerfile: build/package/Dockerfile
  use: buildx
  image_templates:
  - "qumine/minecraft-server:latest-arm64v8"
  - "qumine/minecraft-server:{{.Tag}}-arm64v8"
  goos: linux
  goarch: arm64
  ids:
  - minecraft-server
  build_flag_templates:
  - "--platform=linux/arm64/v8"
  - "--label=org.opencontainers.image.title={{ .ProjectName }}"
  - "--label=org.opencontainers.image.description={{ .ProjectName }}"
  - "--label=org.opencontainers.image.url=https://github.com/qumine/minecraft-server"
  - "--label=org.opencontainers.image.source=https://github.com/qumine/minecraft-server"
  - "--label=org.opencontainers.image.version={{ .Version }}"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
  - "--label=org.opencontainers.image.licenses=AGPL-3.0"
docker_manifests:
- name_template: qumine/minecraft-server:latest
  image_templates:
  - qumine/minecraft-server:latest-amd64
  - qumine/minecraft-server:latest-arm64v8
- name_template: qumine/minecraft-server:{{.Tag}}
  image_templates:
  - qumine/minecraft-server:{{.Tag}}-amd64
  - qumine/minecraft-server:{{.Tag}}-arm64v8
changelog:
  filters:
    exclude:
    - '^ci:'
    - '^docs:'
    - '^misc:'
    - '^test:'