project_name: qumine-server-java
release:
  github:
    owner: qumine
    name: qumine-server-java
  prerelease: auto
before:
  hooks:
  - go mod download
builds:
- goos:
  - linux
  goarch:
  - amd64
  - arm64
  goarm:
  - 6
  - 7
  main: ./cmd/qumine-server-java
  binary: qumine-server-java
  env:
  - CGO_ENABLED=0
archives:
- id: tar_gz
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  files:
  - LICENSE*
  - README*
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
dockers:
- dockerfile: build/package/Dockerfile
  image_templates:
  - "qumine/qumine-server-java:latest-amd64"
  - "qumine/qumine-server-java:{{.Tag}}-amd64"
  goos: linux
  goarch: amd64
  binaries:
  - qumine-server-java
  build_flag_templates:
  - "--build-arg=ARCH=amd64/"
  - "--label=org.opencontainers.image.title={{ .ProjectName }}"
  - "--label=org.opencontainers.image.description={{ .ProjectName }}"
  - "--label=org.opencontainers.image.url=https://github.com/qumine/qumine-server-java"
  - "--label=org.opencontainers.image.source=https://github.com/qumine/qumine-server-java"
  - "--label=org.opencontainers.image.version={{ .Version }}"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
  - "--label=org.opencontainers.image.licenses=AGPL-3.0"
- dockerfile: build/package/Dockerfile
  image_templates:
  - "qumine/qumine-server-java:latest-arm64v8"
  - "qumine/qumine-server-java:{{.Tag}}-arm64v8"
  goos: linux
  goarch: arm64
  binaries:
  - qumine-server-java
  build_flag_templates:
  - "--build-arg=ARCH=arm64v8/"
  - "--label=org.opencontainers.image.title={{ .ProjectName }}"
  - "--label=org.opencontainers.image.description={{ .ProjectName }}"
  - "--label=org.opencontainers.image.url=https://github.com/qumine/qumine-server-java"
  - "--label=org.opencontainers.image.source=https://github.com/qumine/qumine-server-java"
  - "--label=org.opencontainers.image.version={{ .Version }}"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
  - "--label=org.opencontainers.image.licenses=AGPL-3.0"
docker_manifests:
- name_template: qumine/qumine-server-java:latest
  image_templates:
  - qumine/qumine-server-java:latest-amd64
  - qumine/qumine-server-java:latest-arm64v8
- name_template: umine/qumine-server-java:{{.Tag}}
  image_templates:
  - qumine/qumine-server-java:{{.Tag}}-amd64
  - qumine/qumine-server-java:{{.Tag}}-arm64v8
changelog:
  filters:
    exclude:
    - '^ci:'
    - '^docs:'
    - '^misc:'
    - '^test:'