{
 "title": "QuMine Server",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(mc_players_total, service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "TPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TPS",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mc_tps{service=\"$service\"}"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(mc_tps{service=\"$service\"})",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "Tick Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(mc_tick_duration_max{service=\"$service\"})",
     "legendFormat": "MAX"
    },
    {
     "expr": "sum(mc_tick_duration_median{service=\"$service\"})",
     "legendFormat": "MEDIAN"
    },
    {
     "expr": "sum(mc_tick_duration_average{service=\"$service\"})",
     "legendFormat": "AVG"
    },
    {
     "expr": "mc_tick_duration_min{service=~\"$server_name\"}",
     "legendFormat": "MIN"
    }
   ]
  },
  {
   "title": "Loaded Chunks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mc_loaded_chunks_total{service=\"$service\"}) by (world)",
     "legendFormat": "{{world}}"
    }
   ]
  },
  { "title": "Entities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Players Online",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(mc_players_online_total{service=\"$service\"})"
    }
   ]
  },
  {
   "title": "Players",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mc_players_total{service=\"$service\"})",
     "legendFormat": "Unique"
    },
    {
     "expr": "sum(mc_players_online_total{service=\"$service\"}) by (world)",
     "legendFormat": "Online ({{world}})"
    }
   ]
  },
  {
   "title": "Entities",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mc_entities_total{service=\"$service\"}) by (world)",
     "legendFormat": "{{world}}_total"
    }
   ]
  },
  {
   "title": "Villagers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (mc_villagers_total{service=\"$service\"}) by (world, level, profession)",
     "legendFormat": "{{world}}:  {{profession}}  (lv{{level}})"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "JVM Memory",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mc_jvm_memory{type='allocated', service=\"$service\"} - scalar(mc_jvm_memory{type='free', service=\"$service\"})"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(mc_jvm_memory{type='allocated', service=\"$service\"})",
     "legendFormat": "Allocated"
    },
    {
     "expr": "sum(mc_jvm_memory{type='max', service=\"$service\"})",
     "legendFormat": "MAX Allocated"
    },
    {
     "expr": "sum(mc_jvm_memory{type='allocated', service=\"$service\"}) - scalar(sum(mc_jvm_memory{type='free', service=\"$service\"}))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mc_jvm_threads_current{service=\"$service\"}"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mc_jvm_threads_current{service=~\"$service\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "sum(mc_jvm_threads_daemon{service=~\"$service\"})",
     "legendFormat": "Daemon"
    },
    {
     "expr": "sum(mc_jvm_threads_deadlocked{service=~\"$service\"})",
     "legendFormat": "Deadlocked"
    }
   ]
  }
 ]
}